language: cpp

compiler:
  - gcc

# by default Ubuntu Trusty is included, so we have 14.04 + 16.04
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

addons:
  apt:
    packages:
      - cmake
      - libboost-all-dev
      - libeigen3-dev


install:
  - git clone git://github.com/ethz-asl/libnabo.git
  - cd libnabo
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - make
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DBUILD_TESTS=ON --build . ..
  - make -j2
  - ctest --verbose