- SurfaceNormalDataPointsFilter:
   knn:           20
   keepDensities: 1
   keepNormals:   1
- SimpleSensorNoiseDataPointsFilter
- BoundingBoxDataPointsFilter:
   xMin:          -4.0
   xMax:          4.0
   yMin:          -4.0
   yMax:          4.0
   zMin:          -4.0
   zMax:          4.0
   removeInside:  1
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter
- MaxDensityDataPointsFilter:
    maxDensity:   65000
- RemoveNaNDataPointsFilter:
- RandomSamplingDataPointsFilter:
    prob:         0.4
