sensors:
  - id:                                    3da6d03bd42e41a93dc941bd5fd9353d
    sensor_type:                           IMU
    description:                           "Bosch BMI085"
    topic:                                 /alphasense/imu
    sigmas:
      acc_bias_random_walk_noise_density:  0.05
      acc_noise_density:                   0.1
      gyro_bias_random_walk_noise_density: 0.01
      gyro_noise_density:                  0.2
    saturation_accel_max_mps2:             50
    saturation_gyro_max_radps:             6.0
    gravity_magnitude_mps2:                9.81205


  - id:                                    bbf123479caf7592b35518478a2fe08d
    sensor_type:                           LIDAR
    description:                           "Pandar"
    topic:                                 /hesai/pandar

  - id:                                    acbb23479caf7592b35518478a2fe08f
    sensor_type:                           ODOMETRY_6DOF
    description:                           "FAST-LIO2"
    topic:                                 /fastlio2/odom
    T_St_Stp1_fixed_covariance:
      rows:                                6
      cols:                                6
      data:
        - [0.0001, 0.0,  0.0,  0.0,   0.0,   0.0]
        - [0.0,  0.0001, 0.0,  0.0,   0.0,   0.0]
        - [0.0,  0.0,  0.0001, 0.0,   0.0,   0.0]
        - [0.0,  0.0,  0.0,  0.005,  0.0,   0.0]
        - [0.0,  0.0,  0.0,  0.0,   0.005,  0.0]
        - [0.0,  0.0,  0.0,  0.0,   0.0,   0.005]

  - id: ff000000000000000000000000000001
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features0
    target_sensor: 9da9c2fa16894a059f8b40740c721cb1
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000002
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features1
    target_sensor: 44ed7e1913a847b3b8d9884b9b02fb03
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000004
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features3
    target_sensor: da7d19d6662f4a428240bf7f706bbb4d
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000005
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features4
    target_sensor: c70f9347314d4c26a72280c1f193b47d
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id:                                    4af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type:                           NCAMERA
    description:                           "Alphasense"
    topic:                                 ""
    cameras:
      - camera:
          id:                              9da9c2fa16894a059f8b40740c721cb1
          sensor_type:                     CAMERA
          description:                     "Forward 0"
          topic:                           /alphasense/cam0
          line-delay-nanoseconds:          0
          image_height:                    540
          image_width:                     720
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 351.31400364193297
              - 351.4911744656785
              - 367.8522793375995
              - 253.8402144980996
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.03696737352869157
                - -0.008917880497032812
                - 0.008912969593422046
                - -0.0037685977496087313
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.0067080214518005, 0.0024256436418035, 0.9999745590269414, 0.0512635496824681]
            - [0.9999264200621182, 0.0100911970216883, -0.0067321767970211, 0.0453901220122368]
            - [-0.0101072701536599, 0.9999461405473763, -0.0023577731969992, -0.0132149126987094]
            - [0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]

      - camera:
          id:                              44ed7e1913a847b3b8d9884b9b02fb03
          sensor_type:                     CAMERA
          description:                     "Forward 1"
          topic:                           /alphasense/cam1
          line-delay-nanoseconds:          0
          image_height:                    540
          image_width:                     720
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 352.6489794433894
              - 352.8586498571586
              - 347.8170010310082
              - 270.5806692485468
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.039086652082708805
                - -0.005525347047415151
                - 0.004398151558986798
                - -0.0019701263170917808
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.0016556126470598, 0.0009350089535379, 0.9999981923508761, 0.0503920182199237]
            - [0.9999840642813064, 0.0053956906150397, -0.0016606342845621, -0.0627831669975007]
            - [-0.0053972335694490, 0.9999850060281121, -0.0009260608798764, -0.0131432680426853]
            - [0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]

      - camera:
          id:                              da7d19d6662f4a428240bf7f706bbb4d
          sensor_type:                     CAMERA
          description:                     "Sideways Right"
          topic:                           /alphasense/cam3
          line-delay-nanoseconds:          0
          image_height:                    540
          image_width:                     720
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 352.9514843860555
              - 353.32837903547403
              - 363.93345228274336
              - 266.14511705007413
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                  - -0.03890973498616883
                  - -0.002604676547864069
                  - 0.0004634700730293949
                  - -0.00036698216675371063
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.9998916894135627, 0.0127071404640831, 0.0074254981595154, -0.0027416993947014]
            - [0.0073960416730232, -0.0023635309353156, 0.9999698556902046, 0.0572301653448225]
            - [0.0127243078107145, 0.9999164676625462, 0.0022692923994766, -0.0110114836506446]
            - [0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]

      - camera:
          id:                              c70f9347314d4c26a72280c1f193b47d
          sensor_type:                     CAMERA
          description:                     "Sideways Left"
          topic:                           /alphasense/cam4
          line-delay-nanoseconds:          0
          image_height:                    540
          image_width:                     720
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 351.5132148653381
              - 351.7557554938886
              - 342.8425988673232
              - 259.91793254535776
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.03842764034005408
                - -0.005841411460411122
                - 0.003451041303088915
                - -0.0011463543672005018
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.9999880402484466, 0.0047970088651064, -0.0009529249803789, -0.0065676390423793]
            - [-0.0009424276629319, -0.0021900897852223, -0.9999971576643766, -0.0748375416968655]
            - [-0.0047990822216629, 0.9999860960096796, -0.0021855427584386, -0.0168332753720959]
            - [0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]

extrinsics:
  - sensor_id:                             bbf123479caf7592b35518478a2fe08d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [0.0, -1.0, 0.0, -0.001]
        - [-1.0, 0.0, 0.0, -0.00855]
        - [0.0, 0.0, -1.0, 0.055]
        - [0.0, 0.0, 0.0, 1.0]

  - sensor_id:                             3da6d03bd42e41a93dc941bd5fd9353d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000001
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000002
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000004
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000005
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             acbb23479caf7592b35518478a2fe08f
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             4af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
