sensors:
  - id:                                    3da6d03bd42e41a93dc941bd5fd9353d
    sensor_type:                           IMU
    description:                           "ADIS16445 IMU"
    topic:                                 /alphasense/imu_adis
    sigmas:
      gyro_noise_density:                  0.005
      gyro_bias_random_walk_noise_density: 4e-06
      acc_noise_density:                   0.01
      acc_bias_random_walk_noise_density:  0.0002
    saturation_accel_max_mps2:             150
    saturation_gyro_max_radps:             7.5
    gravity_magnitude_mps2:                9.808083883386614


  - id:                                    bbf123479caf7592b35518478a2fe08d
    sensor_type:                           LIDAR
    description:                           "Lidarmace - Ouster OS0"
    topic:                                 /os_cloud_node/points

  - id:                                    acbb23479caf7592b35518478a2fe08f
    sensor_type:                           ODOMETRY_6DOF
    description:                           "OKVIS"
    topic:                                 /odometry/maplab_odom_T_M_I

  - id: ff000000000000000000000000000001
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features0
    target_sensor: 9da9c2fa16894a059f8b40740c721cb1
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000002
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features1
    target_sensor: 44ed7e1913a847b3b8d9884b9b02fb03
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000003
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features2
    target_sensor: 08faa68c87a84fd5bd1b0305c99b155d
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000004
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features3
    target_sensor: da7d19d6662f4a428240bf7f706bbb4d
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id: ff000000000000000000000000000005
    sensor_type: EXTERNAL_FEATURES
    description: "R2D2 features"
    topic: /maplab_features4
    target_sensor: c70f9347314d4c26a72280c1f193b47d
    has_uncertainties: true
    has_orientations: false
    has_scores: true
    has_scales: true
    has_track_ids: true
    feature_type: R2D2

  - id:                                    4af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type:                           NCAMERA
    description:                           "Alphasense"
    topic:                                 ""
    cameras:
      - camera:
          id:                              9da9c2fa16894a059f8b40740c721cb1
          sensor_type:                     CAMERA
          description:                     "Forward Up"
          topic:                           /alphasense/cam0
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.6093151020301
              - 701.101293415187
              - 703.4368797232662
              - 530.3135591232868
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.04336712917278897
                - 0.006570110977664635
                - -0.007433444882865234
                - 0.002045735457572577
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.999990861752, 0.000628464640, -0.004228645702, -0.052798019321]
            - [-0.004226691177, -0.003079450931, -0.999986325938, -0.078374861539]
            - [-0.000641477954, 0.999995060995, -0.003076766464, -0.026280993585]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              44ed7e1913a847b3b8d9884b9b02fb03
          sensor_type:                     CAMERA
          description:                     "Forward Down"
          topic:                           /alphasense/cam1
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 695.6799690342032
              - 695.6963677952774
              - 707.6186115250404
              - 535.8424658218318
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.04257375303271763
                - 0.006156669659059341
                - -0.00740023108750807
                - 0.002079156107447231
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.999947769741, -0.002969883895, -0.009779446770, 0.054037084732]
            - [0.009764748226, 0.004924013957, -0.999940200101, -0.079155584894]
            - [0.003017860428, -0.999983466801, -0.004894756606, -0.026252820103]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              08faa68c87a84fd5bd1b0305c99b155d
          sensor_type:                     CAMERA
          description:                     "Upwards"
          topic:                           /alphasense/cam2
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.3320644734001
              - 701.3930695259667
              - 718.2957379855827
              - 535.7723187275584
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.03875795980183309
                - -0.00335870139802
                - 0.002251953419219693
                - -0.001103896157374707
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.014300546907, -0.999894900219, -0.002383877780, 0.000674266899]
            - [0.999889344876, 0.014290615401, 0.004132349859, -0.034911565484]
            - [-0.004097848469, -0.002442708854, 0.999988620341, 0.003681908458]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              da7d19d6662f4a428240bf7f706bbb4d
          sensor_type:                     CAMERA
          description:                     "Right"
          topic:                           /alphasense/cam3
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 703.273008904613
              - 702.817765216315
              - 702.8544221078837
              - 537.0703115432012
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.04274407200260321
                - 0.003300870639764364
                - -0.003715716140239516
                - 0.0007495619442311171
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.007315443787, 0.001874707327, -0.999971484470, -0.071180407892]
            - [-0.999967470673, -0.003411133669, 0.007309019364, -0.019610290592]
            - [-0.003397334126, 0.999992424791, 0.001899600300, -0.025381489017]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              c70f9347314d4c26a72280c1f193b47d
          sensor_type:                     CAMERA
          description:                     "Left"
          topic:                           /alphasense/cam4
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.5688257771283
              - 701.5879090005477
              - 699.9764089544163
              - 541.9861934781169
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.04176685726706289
                - 0.002325551400383664
                - -0.00255344913205093
                - 0.0002831633732660714
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.009729884445, -0.003198189286, 0.999947549091, 0.071856313376]
            - [-0.999939989667, -0.005003615651, -0.009745814239, -0.018677598863]
            - [0.005034522165, -0.999982367553, -0.003149312759, -0.025556027643]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

extrinsics:
  - sensor_id:                             bbf123479caf7592b35518478a2fe08d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [-0.009512419028, 0.999954499995, -0.000715418261, 0.000054638802]
        - [-0.999954688116, -0.009512152479, 0.000375062393, -0.037469669768]
        - [0.000368240160, 0.000718953595, 0.999999673753, -0.126682785277]
        - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

  - sensor_id:                             3da6d03bd42e41a93dc941bd5fd9353d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000001
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000002
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000003
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000004
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             ff000000000000000000000000000005
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             acbb23479caf7592b35518478a2fe08f
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             4af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
