sensors:
  - id: 5d2fcf479caf7592b35518478a2fe08f
    sensor_type: IMU
    description: "ADIS-16448 IMU"
    topic: /VersaVIS/imu
    sigmas:
      gyro_noise_density: 0.005
      gyro_bias_random_walk_noise_density: 4e-06
      acc_noise_density: 0.01
      acc_bias_random_walk_noise_density: 0.0002
    saturation_accel_max_mps2: 150
    saturation_gyro_max_radps: 7.5
    gravity_magnitude_mps2: 9.808083883386614

  - id: abf123479caf7592b35518478a2fe08f
    sensor_type: LIDAR
    description: "Lidarstick - Ouster OS1"
    topic: /os1_cloud_node/points

  - id: ffff23479caf7592b35518478a2fe08f
    sensor_type: POINTCLOUD_MAP
    description: "Lidarstick - Ouster OS1 - Throttled"
    topic: /os1_node/points_throttled

  - id: aabb23479caf7592b35518478a2fe08f
    sensor_type: ODOMETRY_6DOF
    description: "ROVIOLI in Odometry mode"
    topic: /odometry/maplab_odom_T_M_I

  - id: 8af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type: NCAMERA
    description: "Lidarstick - Blackfly S 0.4MP (Color/Mono) Stereo Pair"
    topic: ""
    cameras:
      - camera:
          id: 9be7b5000f15adb3c0da8ac6b729ee05
          sensor_type: CAMERA
          description: "Blackfly S 0.4MP Color Camera"
          topic: /VersaVIS/cam0
          line-delay-nanoseconds: 0
          image_height: 540
          image_width: 720
          type: pinhole
          intrinsics:
            rows: 4
            cols: 1
            data:
              - 288.408207812205
              - 288.22311036136836
              - 362.6636545997341
              - 274.6270363549055
          distortion:
            type: equidistant
            parameters:
              rows: 4
              cols: 1
              data:
                - 0.007267463899378662
                - -0.003416892997276599
                - 0.0005955948706648939
                - -0.0004223559610193976
        T_B_C:
          rows: 4
          cols: 4
          data:
            - [-0.9999237459683411, -0.00887049095954965, -0.008591661002224566, -0.03422715855358821]
            - [-0.008578055805414566, -0.0015706688514416207, 0.9999619742560005, 0.05631226626235311]
            - [-0.008883648306849611, 0.9999594228714962, 0.0014944575151368982, 0.05622655837534756]
            - [0, 0, 0, 1]
      - camera:
          id: ac4704b6b1b4cf41b0924ecb7bd863ec
          sensor_type: CAMERA
          description: "Blackfly S 0.4MP Mono Camera"
          topic: /VersaVIS/cam0
          line-delay-nanoseconds: 0
          image_height: 540
          image_width: 720
          type: pinhole
          intrinsics:
            rows: 4
            cols: 1
            data:
              - 290.639512387635
              - 290.49023471411374
              - 364.7735578713057
              - 279.0607406253249
          distortion:
            type: equidistant
            parameters:
              rows: 4
              cols: 1
              data:
                - 0.005164682895585011
                - -0.00014747591274677765
                - -0.0013655429586935683
                - 5.805801080659683e-06
        T_B_C:
          rows: 4
          cols: 4
          data:
            - [-0.9999419764694114, -0.008225515598876082, 0.006955903074364936, -0.16121109473325873]
            - [0.0069566632299703016, -6.380605157241744e-05, 0.9999758000899285, 0.05803178302646453]
            - [-0.008224872713428002, 0.9999661678386528, 0.00012102449123429574, 0.05481953354950948]
            - [0, 0, 0, 1]

extrinsics:
  - sensor_id: abf123479caf7592b35518478a2fe08f
    base_sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [-0.6978447576305695, 0.7161518144580716, 0.01180139381358678, -0.1021019447103219]
        - [0.7160088243900917, 0.697942707663664, -0.01439931299167545, -0.08936602296234536]
        - [-0.01854879087839803, -0.001598582974091693, -0.999826678424528, -0.07460082421278309]
        - [0, 0, 0, 1]

  - sensor_id: ffff23479caf7592b35518478a2fe08f
    base_sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [-0.6978447576305695, 0.7161518144580716, 0.01180139381358678, -0.1021019447103219]
        - [0.7160088243900917, 0.697942707663664, -0.01439931299167545, -0.08936602296234536]
        - [-0.01854879087839803, -0.001598582974091693, -0.999826678424528, -0.07460082421278309]
        - [0, 0, 0, 1]

  - sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    base_sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id: aabb23479caf7592b35518478a2fe08f
    base_sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id: 8af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id: 5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows: 4
      cols: 4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
