# SENSORS AND CALIBRATION
sensor_calibration_file: ""
# IMU
imu_to_camera_time_offset_ns: 0
external_imu_parameters_rovio: ""
# VIO
vio_camera_topic_suffix: ""
vio_nframe_sync_tolerance_ns: 750000
vio_nframe_sync_max_output_frequency_hz: 10

# SENSOR SELECTION
# only needed if there are multiple ncameras/lidars/imus/odometries
# in the calibration file.
selected_ncamera_sensor_id: ""
selected_imu_sensor_id: ""
selected_lidar_sensor_id: ""
selected_odometry_6dof_sensor_id: ""
#rovio_active_camera_indices: 0

# DATA SOURCE [rosbag, rostopic]
datasource_type: "rostopic"
datasource_rosbag: ""

# DATA PREPROCESSING
rovioli_zero_initial_timestamps: false
rovio_image_mask_path: ""
rovioli_image_apply_clahe_histogram_equalization: false

# ROVIO
rovio_enable_frame_visualization: true
rovioli_enable_health_checking: true

# MAP BUILDING
rovioli_run_map_builder: true
save_map_folder: rovioli_map
overwrite_existing_map: false
optimize_map_to_localization_map: false
map_builder_save_image_as_resources: false

# VISUAL LOCALIZATION
vio_localization_map_folder: ""

# TF
tf_map_frame: map
tf_mission_frame: mission
tf_imu_frame: imu

# DEBUGGING AND LOGGING
alsologtostderr: true
colorlogtostderr: true
v: 1
publish_debug_markers: false
vis_default_namespace: maplab_rviz
export_estimated_poses_to_csv: ""
detection_visualize_keypoints: false
feature_tracker_visualize_feature_tracks: true
feature_tracker_visualize_keypoint_matches: true
feature_tracker_visualize_keypoints: false
feature_tracker_visualize_keypoints_individual_frames: false
